### ISSUE TITLE
Road to MVP 

### ISSUE THREAD

**Issue by martinrohbeck** [bioFAM/cellij#5]
The following boxes should be checked for an MVP:

- [ ] Implement base factor analysis model (consisting of #9, #10)
- [ ] Implement priors
  - [ ] Horseshoe
  - [ ] ARD
  - [ ] Spike&Slab
- [ ] Reproduce ground truth synthetic data
  - [ ] Create synthetic (bio-inspired) data (#7) 
- [ ] Reproduce results from MOFA CLL analysis
- [ ] Readme with guidelines on environment setup (#3) and minimal example 
- [ ] Implement MOFA(+) model wrapper
- [ ] Implement tests
- [ ] Documentation for all the parts involved

Each checkbox will have it's own issue. This issue deals solely as an overview, feel free to edit according to your thoughts.
