### ISSUE TITLE
Priority Task List

### ISSUE THREAD

**Issue by martinrohbeck** [bioFAM/cellij#57]
**Priority High**
- [ ] Make sure `get_factors()` and `get_weights` work for all sparsity priors (currently not the case due to sampling procedures)
- [ ] Add a Jeffrey's prior for the variance in the SnSLasso
- [ ] (Testcase) Develop standalone pyro distributions for priors (#20 )
- [x] Provide save and load functionality @timtreis 
- [x] Skip missings in obs during inference @timtreis 
- [x] na_strategy: add impute with means @timtreis 
- [x] Change Black formatter to only work on `merge` @timtreis 
- [x] Add proper Logging @timtreis 
- [ ] Add CUDA support (#56 ) @arberqoku 
- [ ] Implement MOFA+ (#44 )

**Priority Medium**
- [ ] Implement and Experiment with Custom Guide class (#10 )
- [ ] Implement tests for benchmarking metrics
- [x] Add OrderedDict for moments in mofa model @martinrohbeck 
- [x] Log number of missings when new dataset is added @timtreis 

**Priority Low**
- [ ] (unclear) scale all modalities according to features and likelihoods?
